/*
 * Copyright 2026 Scalar Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.scalar.re.sdk.processor;

/**
 * Represents a single record to be written to re_inbox.
 *
 * Generated by InboxEntryProcessor from a ReEventBody based on
 * delivery mode and routing configuration.
 */
public class InboxEntry {

    private final String routingDestination;
    private final int stepId;
    private final int seq;
    private final boolean ackRequired;
    private final String body;

    public InboxEntry(String routingDestination, int stepId, int seq, boolean ackRequired, String body) {
        this.routingDestination = routingDestination;
        this.stepId = stepId;
        this.seq = seq;
        this.ackRequired = ackRequired;
        this.body = body;
    }

    /**
     * Routing destination in namespace.table format.
     */
    public String getRoutingDestination() {
        return routingDestination;
    }

    /**
     * step_id for re_inbox CK.
     * atomic: 0, sequential: actual step id.
     */
    public int getStepId() {
        return stepId;
    }

    /**
     * seq for re_inbox CK.
     * atomic: 0, sequential: actual seq value.
     */
    public int getSeq() {
        return seq;
    }

    /**
     * Whether ack is required for this routing destination.
     */
    public boolean isAckRequired() {
        return ackRequired;
    }

    /**
     * Re-constructed body JSON for this inbox record.
     */
    public String getBody() {
        return body;
    }

    @Override
    public String toString() {
        return "InboxEntry{destination=" + routingDestination
                + ", stepId=" + stepId
                + ", seq=" + seq
                + ", ackRequired=" + ackRequired
                + "}";
    }
}
